config/routes.rb
Rails.application.routes.draw do
  resources :day_shifts
  resources :shifts
  resources :service_duties
  resources :services
  resources :employees
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :service_duties
    has_many :day_shifts

    def employee_shifts(selected_date = Date.today)
        employee_shifts_count = self.day_shifts.shifts(selected_date).select(:employee_id).group(:employee_id).count
        nil_values = self.day_shifts.shifts(selected_date).pluck(:employee_id).select(&:nil?).count
        if employee_shifts_count.keys.first.blank?
            employees = [] 
        else
            employees = Employee.find(employee_shifts_count.keys)
        end
        employees.map{ |employee| { name: employee.name || 'Sin Asignar', shifts: employee_shifts_count[employee.id].to_i, color: employee.color }} << { name: 'Sin Asignar', shifts: nil_values.to_i}
    end

    def last_service_week
        day_shifts.order(:date).last.nil? ? Time.now.beginning_of_week : day_shifts.order(:date).last.date.beginning_of_week
    end

    def this_week_shifts(selected_date = Date.today)
        day_shifts.where("date >= ? AND date <= ?", selected_date.to_date.beginning_of_week, selected_date.to_date.end_of_week)
    end

    def has_shifts?
        day_shifts.size == 0
    end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_cal.slim
.col-4
    / button data-id="#{service.id}" data-date="#{date}" data-reflex='click->Service#previous' atras
    = link_to root_path(date: date-1.week, service: service.id) do 
        i.fas.fa-chevron-left.fa-3x
.col-4 
    h5 = "Semana #{date.cweek} del #{date.year}"
.col-4
    / button data-id="#{service.id}" data-date="#{date}" data-reflex='click->Service#next' siguiente
    = link_to root_path(date: date+1.week, service: service.id) do 
        i.fas.fa-chevron-right.fa-3x

app/views/services/_form.html.slim
= form_for @service do |f|
  - if @service.errors.any?
    #error_explanation
      h2 = "#{pluralize(@service.errors.count, 'error')} prohibited this service from being saved:"
      ul
        - @service.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/services/_header.slim
h3 = service.name

app/views/services/_list.slim
- Service.all.each do |service|
    li.list-group-item = service.name

app/views/services/_menu.slim
h1 MENU
.row 
    = link_to 'Crear Horario', service_duties_path

app/views/services/edit.html.slim
h1 Editing service

== render 'form'

=> link_to 'Show', @service
'|
=< link_to 'Back', services_path

app/views/services/index.html.slim
.container
  h1 Listing services

  = link_to 'New Service', new_service_path
  table.table
    thead
      tr
        th Name
        th
        th
        th

    tbody
      - @services.each do |service|
        tr
          td = service.name
          td = link_to 'Show', service
          td = link_to 'Edit', edit_service_path(service)
          td = link_to 'Destroy', service, data: { confirm: 'Are you sure?' }, method: :delete

app/views/services/new.html.slim
h1 New service

== render 'form'

= link_to 'Back', services_path

app/views/services/show.html.slim
p#notice = notice

p
  strong Name:
  = @service.name

=> link_to 'Edit', edit_service_path(@service)
'|
=< link_to 'Back', services_path