config/routes.rb
Rails.application.routes.draw do
  resources :day_shifts
  resources :shifts
  resources :service_duties
  resources :services
  resources :employees
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/day_shift.rb
class DayShift < ApplicationRecord
  belongs_to :service
  has_many :shifts

  def self.shifts(selected_date = Date.today)
    joins(:shifts).where("date >= ? AND date <= ?", selected_date.to_date.beginning_of_week, selected_date.to_date.end_of_week)
  end
end

app/controllers/day_shifts_controller.rb
class DayShiftsController < ApplicationController
  before_action :set_day_shift, only: %i[ show edit update destroy ]

  # GET /day_shifts or /day_shifts.json
  def index
    @day_shifts = DayShift.all
  end

  # GET /day_shifts/1 or /day_shifts/1.json
  def show
  end

  # GET /day_shifts/new
  def new
    @day_shift = DayShift.new
  end

  # GET /day_shifts/1/edit
  def edit
  end

  # POST /day_shifts or /day_shifts.json
  def create
    @day_shift = DayShift.new(day_shift_params)

    respond_to do |format|
      if @day_shift.save
        format.html { redirect_to @day_shift, notice: "Duty shift was successfully created." }
        format.json { render :show, status: :created, location: @day_shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @day_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_shifts/1 or /day_shifts/1.json
  def update
    respond_to do |format|
      if @day_shift.update(day_shift_params)
        format.html { redirect_to @day_shift, notice: "Duty shift was successfully updated." }
        format.json { render :show, status: :ok, location: @day_shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @day_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_shifts/1 or /day_shifts/1.json
  def destroy
    @day_shift.destroy
    respond_to do |format|
      format.html { redirect_to day_shifts_url, notice: "Duty shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_shift
      @day_shift = DayShift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def day_shift_params
      params.require(:day_shift).permit(:date, :service_id)
    end
end

app/helpers/day_shifts_helper.rb
module DayShiftsHelper
end

app/views/day_shifts/_avaliability_table.slim
.row
    .col-3 id='service_header'
        h3 = service.name
    .col-3 id="service_button"
        button.btn.btn-primary data-id="#{service.id}" data-reflex="click->Service#asign_times" Asignar Horarios
.row 
    / p = "Semana #{service.start_time.strftime("%W")} del #{service.start_time.strftime("%Y")}"
    p del 02/02/2020 al 08/02/2020
.row
    .col-6
        table 
            - service.day_shifts.each do |day_shift|
                tr
                    th = day_shift.date.strftime("%A %d, %B")
                    - Employee.all.each do |employee|
                        th = employee.name
                    - day_shift.shifts.each do |shift|
                        tr 
                            td = "#{shift.start_time.strftime('%H:%M')} - #{(shift.start_time+shift.duration.hour).strftime('%H:%M')}"
                            - Employee.all.each do |employee|
                                td id="d#{shift.id}_e#{employee.id}"
                                    .form-check
                                        - if shift.employees.include?(employee)
                                            input.form-check-input type="checkbox" id="flexCheckDefault" data-employee="#{employee.id}" data-shift="#{shift.id}" checked="1" data-reflex="change->DayShift#set_employee_avaliability"
                                        - else 
                                            input.form-check-input type="checkbox" id="flexCheckDefault" data-employee="#{employee.id}" data-shift="#{shift.id}" data-reflex="change->DayShift#set_employee_avaliability"

app/views/day_shifts/_checkbox.slim
.form-check
    - if selected
        input.form-check-input type="checkbox" id="flexCheckDefault" data-employee="#{employee}" data-day_shift="#{day_shift}" checked="true" data-reflex="change->DayShift#set_employee_avaliability"
    - else
        input.form-check-input type="checkbox" id="flexCheckDefault" data-employee="#{employee}" data-day_shift="#{day_shift}" data-reflex="change->DayShift#set_employee_avaliability"

app/views/day_shifts/_form.html.slim
= form_for @day_shift do |f|
  - if @day_shift.errors.any?
    #error_explanation
      h2 = "#{pluralize(@day_shift.errors.count, 'error')} prohibited this day_shift from being saved:"
      ul
        - @day_shift.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :date
    = f.datetime_select :date
  .field
    = f.label :service_id
    = f.text_field :service_id
  .actions = f.submit

app/views/day_shifts/_table.slim
.row
    .col-3 id='service_header'
        h3 = service.name
    .col-3 id="service_button"
        button.btn.btn-primary data-id="#{service.id}" data-reflex="click->Service#asign_avaliabilities" Disponibilidad
.row 
    .col-3
        table 
            - service.employee_shifts.each do |employee|
                tr 
                    th = employee[:name]
                    td = employee[:shifts]
.row
    
.row
    - service.day_shifts.each do |shift|
        .col-3
            table
                tr
                    th colspan="2" = shift.start_time
                
                tr 
                    td = "#{shift.start_time.strftime('%H:%M')} - #{(shift.start_time+shift.duration.hour).strftime('%H:%M')}"
                    td Jorge

app/views/day_shifts/edit.html.slim
h1 Editing day_shift

== render 'form'

=> link_to 'Show', @day_shift
'|
=< link_to 'Back', day_shifts_path

app/views/day_shifts/index.html.slim
h1 Listing day_shifts

table
  thead
    tr
      th date
      th Service
      th
      th
      th

  tbody
    - @day_shifts.each do |day_shift|
      tr
        td = day_shift.date
        td = day_shift.service.name
        td = link_to 'Show', day_shift
        td = link_to 'Edit', edit_day_shift_path(day_shift)
        td = link_to 'Destroy', day_shift, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Duty shift', new_day_shift_path

app/views/day_shifts/new.html.slim
h1 New day_shift

== render 'form'

= link_to 'Back', day_shifts_path

app/views/day_shifts/show.html.slim
p#notice = notice

p
  strong date:
  = @day_shift.date

p
  strong Service: 
  = @day_shift.service.name


=> link_to 'Edit', edit_day_shift_path(@day_shift)
'|
=< link_to 'Back', day_shifts_path