config/routes.rb
Rails.application.routes.draw do
  resources :day_shifts
  resources :shifts
  resources :service_duties
  resources :services
  resources :employees
  root 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :day_shift
  belongs_to :employee, optional: true
  has_and_belongs_to_many :employees

  def table_color
    if self.employee.nil?
      ''
    elsif self.employee.color == 'red'
      'table-danger'
    elsif self.employee.color == 'blue'
      'table-primary'
    elsif self.employee.color == 'yellow'
      'table-warning'
    elsif self.employee.color == 'lightblue'
      'table-info'
    elsif self.employee.color == 'grey'
      'table-secondary'
    elsif self.employee.color == 'green'
      'table-success'
    else
      'table-success'
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[ show edit update destroy ]

  # GET /shifts or /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1 or /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts or /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: "Shift was successfully created." }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1 or /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: "Shift was successfully updated." }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1 or /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:start_time, :duration, :day_shift_id, :employee_id)
    end
end

app/views/shifts/_avaliability_table.slim
- if service.has_shifts?
    .row
        = render partial: 'services/menu', locals: { service: service, date: date }
- else
    .row
        .col-3 id='service_header'
            h3 = service.name
        .col-3 id="service_button"
            button.btn.btn-primary data-id="#{service.id}" data-date="#{service.this_week_shifts(date).first.nil? ? '' : service.this_week_shifts(date).first.date}" data-reflex="click->Service#asign_times" Asignar Horarios
    .row 
        / p del #{service.this_week_shifts(date).first.date.beginning_of_week.strftime("%d/%m/%Y")} al #{service.this_week_shifts(date).first.date.end_of_week.strftime("%d/%m/%Y")}
    .row
        .col-10
            table.table
                - service.this_week_shifts(date).each do |day_shift|
                    tr
                        th = day_shift.date.strftime("%A %d, %B")
                        - Employee.all.each do |employee|
                            th = employee.name
                        - day_shift.shifts.order(:start_time).each do |shift|
                            tr 
                                td = "#{shift.start_time.strftime('%H:%M')} - #{(shift.start_time+shift.duration.hour).strftime('%H:%M')}"
                                - Employee.all.each do |employee|
                                    td id="d#{shift.id}_e#{employee.id}"
                                        .form-check
                                            - if shift.employees.include?(employee)
                                                input.form-check-input type="checkbox" data-employee="#{employee.id}" data-shift="#{shift.id}" checked="true" data-reflex="change->Shift#set_employee_avaliability"
                                            - else 
                                                input.form-check-input type="checkbox" data-employee="#{employee.id}" data-shift="#{shift.id}" data-reflex="change->Shift#set_employee_avaliability"

app/views/shifts/_checkbox.slim
.form-check
    - if selected
        input.form-check-input type="checkbox" data-employee="#{employee}" data-shift="#{shift}" checked="true" data-reflex="change->Shift#set_employee_avaliability"
    - else
        input.form-check-input type="checkbox" data-employee="#{employee}" data-shift="#{shift}" data-reflex="change->Shift#set_employee_avaliability"

app/views/shifts/_employees.slim
.col-3
    table.table
        - employee_shifts.each do |employee|
            tr class="#{table_color(employee[:color])}"
                th = employee[:name]
                td = employee[:shifts]

app/views/shifts/_form.html.slim
= form_for @shift do |f|
  - if @shift.errors.any?
    #error_explanation
      h2 = "#{pluralize(@shift.errors.count, 'error')} prohibited this shift from being saved:"
      ul
        - @shift.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :duration
    = f.number_field :duration
  .field
    = f.label :day_shift_id
    = f.text_field :day_shift_id
  .field
    = f.label :employee_id
    = f.text_field :employee_id
  .actions = f.submit

app/views/shifts/_table.slim
- if service.has_shifts?
    .row
        = render partial: 'services/menu', locals: { service: service, date: date }
- else
    .row
        .col-3 id='service_header'
            h3 = service.name
        .col-3 id="service_button"
            button.btn.btn-primary data-id="#{service.id}" data-date="#{service.this_week_shifts(date).first.nil? ? '' : service.this_week_shifts(date).first.date}" data-reflex="click->Service#asign_avaliabilities" Disponibilidad
    .row id="shift_employees_s#{service.id}_d#{service.this_week_shifts(date).first.nil? ? '0' : service.this_week_shifts(date).first.date.cweek}"
        = render partial: 'shifts/employees', locals: { employee_shifts: service.employee_shifts(date) }
    .row
        
    .row
        - service.this_week_shifts(date).each do |day_shift|
            .col-6
                table.table
                    tr
                        th colspan="2" = day_shift.date.strftime("%A %d, %B")
                    - day_shift.shifts.order(:start_time).each do |shift|
                        tr id="#{dom_id(shift)}"
                            = render partial: 'shifts/table_row', locals: {shift: shift, service: service, day_shift: day_shift}
                            

app/views/shifts/_table_row.slim
td class="#{shift.employee_id.to_i > 0 ? 'table-success' : 'table-danger'}"
    = "#{shift.start_time.strftime('%H:%M')} - #{(shift.start_time+shift.duration.hour).strftime('%H:%M')}"
- if shift.employees.size == 0
    td class="#{shift.table_color}" 
        i.fas.fa-exclamation-triangle
        |Sin Disponibilidad
-else
    td class="#{shift.table_color}" = select_tag :employee, options_for_select(shift.employees.pluck(:name, :id), {:selected => shift.employee_id}), { :include_blank => true, data: { service: service.id, date: day_shift.date, reflex: 'change->Shift#set_shift_employee', shift: shift.id}}

app/views/shifts/edit.html.slim
h1 Editing day_shift

== render 'form'

=> link_to 'Show', @shift
'|
=< link_to 'Back', shifts_path

app/views/shifts/index.html.slim
h1 Listing shifts

table
  thead
    tr
      th Start time
      th Duration
      th Day shift
      th Employee
      th
      th
      th

  tbody
    - @shifts.each do |shift|
      tr
        td = shift.start_time.strftime('%H:%M')
        td = shift.duration
        td = shift.day_shift.date
        td = shift.employee
        td = link_to 'Show', shift
        td = link_to 'Edit', edit_shift_path(shift)
        td = link_to 'Destroy', shift, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Duty shift', new_shift_path

app/views/shifts/new.html.slim
h1 New shift

== render 'form'

= link_to 'Back', shifts_path

app/views/shifts/show.html.slim
p#notice = notice

p
  strong Start time:
  = @shift.start_time

p
  strong Duration:
  = @shift.duration

p
  strong day shift:
  = @shift.day_shift

p
  strong Employee:
  = @shift.employee

=> link_to 'Edit', edit_shift_path(@shift)
'|
=< link_to 'Back', shifts_path